services:
  meloTTS:
    image: melotts:latest
    volumes:
      - ./melo:/app/melo
    ports:
      - "8888:8888"
    command: uvicorn melo.app:app --host 0.0.0.0 --port 8888 --reload
    #command: python ./melo/app.py --host 0.0.0.0 --port 8888 
    extra_hosts:
      - "host.docker.internal:host-gateway"

